# muss man hier definieren, sonst klappt das nicht für beide includes
stages:
  - deploy-test
  - deploy-prod

include:
  # use template for gitlab pipeline to deploy to shinyapps.io
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "feature-extend"
    file: "deploy-to-shinyapps.yml"
  # use template for gitlab pipeline to push main to github 
  - project: "OE-7035/ssz-da/templates/pipeline-templates"
    ref: "feature-extend"
    file: "publish-to-github.yml"

deploy-job-test:
  extends:
    - .deploy-job-test

deploy-job-prod:
  extends:
    - .deploy-job-prod

publish-main-to-github:
  extends:
    - .publish-main-to-github
  script:
    - !reference [.git-setup, script]
    - git push -u github main

    