
  
variables:
  CONTAINER_REGISTRY: $CI_REGISTRY
  CONTAINER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  CONTAINER_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CONTAINER_REPOSITORY: $SWID
  CONTAINER_IMAGE_NAME: $CI_PROJECT_NAME # used for container image name
  COMPONENT_NAME: $CI_PROJECT_NAME # used for component name (alias name) in umbrella chart
  GIT_STRATEGY: fetch

include:
  - project: 'cmp-common/cmp-build-common'
    ref: release/2.0
    file: 'gitlab-ci-template.yaml'
  
stages:          # List of stages for jobs, and their order of execution
  - package
  - deploy_test
  - deploy_prod

image-build:
  extends: ".image-build"
  stage: package
  variables:
    CONTEXT_PATH: $CI_PROJECT_DIR/$DOCKER_DIR
    DOCKERFILE: $CI_PROJECT_DIR/$DOCKER_DIR/Dockerfile
    IMAGE_NAME: $CI_PROJECT_NAME
    IMAGE_VERSION: 0.0.0.9001
  rules:
    - changes: 
      - renv.lock

.template-deploy-job:
  image: $CI_REGISTRY/ssz-da/lima_golem:0.0.0.9001
  script:
  - Rscript -e "renv::deactivate()"
  - Rscript -e "packageVersion('rsconnect')"
  - Rscript -e "installed.packages()"
  - Rscript -e "source('deploy.R')"
  
deploy-job-test:
  # ausgeführt wenn push in merge request
  extends: .template-deploy-job
  stage: deploy_test
  variables:
    APP_NAME: $TEST_NAME
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  environment:
    name: test
    url: https://${SHINY_ACC_NAME}.shinyapps.io/${APP_NAME}

 
deploy-job-prod:
  # ausgeführt wenn Push auf Main branch
  extends: .template-deploy-job
  stage: deploy_prod
  variables:
    APP_NAME: $PROD_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: prod
    url: https://${SHINY_ACC_NAME}.shinyapps.io/${APP_NAME}
