default:
  image: $CI_REGISTRY/docker-hub-proxy/rocker/tidyverse:4.2.1
  
variables:
  CONTAINER_REGISTRY: $CI_REGISTRY
  CONTAINER_REGISTRY_USERNAME: $CI_REGISTRY_USER
  CONTAINER_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  CONTAINER_REPOSITORY: $SWID
  CONTAINER_IMAGE_NAME: $CI_PROJECT_NAME # used for container image name
  COMPONENT_NAME: $CI_PROJECT_NAME # used for component name (alias name) in umbrella chart
  GIT_STRATEGY: fetch
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library

# cache:
#   key: ${CI_PROJECT_DIR}
#   paths:
#     - ${RENV_PATHS_CACHE}
#     - ${RENV_PATHS_LIBRARY}

include:
  - project: 'cmp-common/cmp-build-common'
    ref: release/2.0
    file: 'gitlab-ci-template.yaml'
  
stages:          # List of stages for jobs, and their order of execution
  - package
  - restore_renv
  - deploy_test
  - deploy_prod

image-build:
  extends: ".image-build"
  stage: package
  variables:
    CONTEXT_PATH: $CI_PROJECT_DIR/$DOCKER_DIR
    DOCKERFILE: $CI_PROJECT_DIR/$DOCKER_DIR/Dockerfile
    IMAGE_NAME: $CI_PROJECT_NAME
    BUILD_ARGS: "--build-arg RENV_PATHS_LIBRARY=$RENV_PATHS_LIBRARY --build-arg DIR_TO_USE=$CONTEXT_PATH"
    IMAGE_VERSION: 0.0.0.9001
  rules:
    - if:
      changes: 
        - renv.lock
        - Dockerfile

# restore-renv-job:
#   stage: restore_renv
#   script:
#   - Rscript -e "if (!requireNamespace('renv', quietly = TRUE)) install.packages('renv')"
#   - Rscript -e "renv::restore()"
  # rules:
  #    - if:
  #      changes: 
  #        - renv.lock


.template-deploy-job:
  image: $CI_REGISTRY/ssz-da/lima-golem:0.0.0.9001
  script:
  - ls
  - Rscript -e "renv::activate()"
  - Rscript -e "renv::status()"
  - Rscript -e "installed.packages()"
  - echo $CI_PROJECT_DIR
  - Rscript -e "packageVersion('rsconnect')"
  - Rscript -e "source('dev/deploy.R')"
  
deploy-job-test:
  # ausgeführt wenn push in merge request
  extends: .template-deploy-job
  stage: deploy_test
  variables:
    APP_NAME: $TEST_NAME
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  environment:
    name: test
    url: https://${SHINY_ACC_NAME}.shinyapps.io/${APP_NAME}

 
deploy-job-prod:
  # ausgeführt wenn Push auf Main branch
  extends: .template-deploy-job
  stage: deploy_prod
  variables:
    APP_NAME: $PROD_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment:
    name: prod
    url: https://${SHINY_ACC_NAME}.shinyapps.io/${APP_NAME}
